### ISSUE TITLE
bulk push notifications

### ISSUE THREAD

**Issue by Gurudevdatta** [gonzaloaune/GCMPushPlugin#23]
I want to know is there any way to send push notification to multiple devices at a time..in "to" parameter can we able to pass array of the registered device ids..
The curl syntax,
curl --header "Authorization: key=SERVER_API_KEY" \
       --header Content-Type:"application/json" \
       https://gcm-http.googleapis.com/gcm/send \
       -d "{ \"data\" : { \"title\" : \"MyCoolApp\", \"text\" : \"MessageText\", \"extra\":{\"url\":\"someurl.js\"}}, \"to\" : \"$DEVICE_TOKEN\" }"

**Comment by malah-code** [comment]
Also it's not related to the plugin, you can check the details below
https://developers.google.com/cloud-messaging/http-server-ref#send-downstream

**Comment by Gurudevdatta** [comment]
Thanks..that was really helpful.
